# Generated by Django 4.2 on 2026-03-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('espèces', 'Espèces'), ('carte', 'Carte'), ('virement', 'Virement')], default='carte', max_length=20)),
                ('statut', models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('remboursé', 'Remboursé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='rentals.reservation')),
            ],
        ),
    ]
