# Generated by Django 4.2 on 2026-03-21 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_client_cin'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='banque_virement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_especes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_virement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('espèces', 'Espèces'), ('carte', 'Carte'), ('virement', 'Virement'), ('mixte', 'Mixte')], default='carte', max_length=20),
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_avance', models.DateField()),
                ('montant_especes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('montant_cheque', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=50)),
                ('banque_cheque', models.CharField(blank=True, max_length=100)),
                ('montant_cheque2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('numero_cheque2', models.CharField(blank=True, max_length=50)),
                ('banque_cheque2', models.CharField(blank=True, max_length=100)),
                ('montant_virement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('banque_virement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='rentals.reservation')),
            ],
        ),
    ]
