# Generated by Django 4.2 on 2026-05-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contrat_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='actif', max_length=20),
        ),
    ]
