# Generated by Django 4.2 on 2026-03-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
