# Generated by Django 4.2 on 2026-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_client_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='a_accident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='accident_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_apres_bosses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_apres_carburant',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_apres_eraflures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_apres_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_apres_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_apres_propre',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_avant_bosses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_avant_carburant',
            field=models.CharField(blank=True, default='plein', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_avant_eraflures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_avant_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_avant_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat_avant_propre',
            field=models.BooleanField(default=True),
        ),
    ]
