# Generated by Django 4.2 on 2026-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_client_note_reservation_a_accident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='caution',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
