# Generated by Django 4.2 on 2026-04-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_prix_haute_saison_and_more'),
        ('rentals', '0004_reservation_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='raison_remplacement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicule_remplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_remplacement', to='vehicles.vehicle'),
        ),
    ]
