# Generated by Django 4.2 on 2026-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='points_fidelite_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='points_gagnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='points_utilises',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='reduction_fidelite_pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='client',
            name='reduction_wallet_pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
