# Generated by Django 4.2 on 2026-06-05 13:55
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0004_alter_vehicle_statut'),  # ✅ FIX: 0005 supprimée → 0004
        ('rentals', '0007_client_points_fidelite_pending_client_points_gagnes_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='client',
            name='solde_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='acompte_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='rentals.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('client', 'vehicle')},
            },
        ),
    ]