# Generated by Django 4.2 on 2026-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_reservation_bosses_retour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checklist_retour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_inspection',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
