# Generated by Django 4.2 on 2026-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_points_utilises_user_solde_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_fidelite_pending',
            field=models.IntegerField(default=0, help_text='Points fidélité consommés pour la réduction en attente'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduction_fidelite_pending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction fidélité à appliquer sur la prochaine réservation', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='reduction_wallet_pending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction wallet à appliquer sur la prochaine réservation', max_digits=10),
        ),
    ]
