# Generated by Django 4.2 on 2026-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, max_length=30)),
                ('prix_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loué', 'Loué'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
