# Generated by Django 4.2 on 2026-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assurance_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assurance_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_controle_technique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_derniere_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='etat_carrosserie',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kilometrage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='nombre_places',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type_carburant',
            field=models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('électrique', 'Électrique'), ('hybride', 'Hybride')], default='essence', max_length=20),
        ),
    ]
