# Generated by Django 4.2 on 2026-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_assurance_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='prix_haute_saison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='prix_tres_haute_saison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='etat_carrosserie',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometrage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='nombre_places',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prix_journalier',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_carburant',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('électrique', 'Électrique'), ('hybride', 'Hybride')], default='essence', max_length=20),
        ),
    ]
