# Generated by Django 4.2 on 2026-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_prix_haute_saison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('loué', 'Loué'), ('maintenance', 'Maintenance'), ('hors_service', 'Hors service'), ('a_vendre', 'À vendre'), ('vendu', 'Vendu')], default='disponible', max_length=20),
        ),
    ]
