# Generated by Django 4.2 on 2026-06-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_acquisition',
            field=models.DateField(blank=True, help_text="Date d'achat/entrée en flotte — seuil 3.5 ans pour recommander la vente", null=True),
        ),
    ]
